name: Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  CTEST_OUTPUT_ON_FAILURE: 1
  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    
    - name: test local build
      run: |
        cmake -S test -B build/local
        cmake --build build/local 
        ./build/local/test

    - name: install dependency
      run: |
        cmake -S test/dependency -B build/dependency
        sudo cmake --build build/dependency --target install
        cmake -S test/dependency2 -B build/dependency2
        sudo cmake --build build/dependency2 --target install

    - name: test installed build
      run: |
        cmake -S test -B build/installed -D TEST_INSTALLED_VERSION=1
        cmake --build build/installed 
        ./build/installed/test
